ssh.yml: use nothing-but-nix for cleanup

diff --git a/.github/workflows/ssh.yml b/.github/workflows/ssh.yml
--- a/.github/workflows/ssh.yml
+++ b/.github/workflows/ssh.yml
@@ -21,11 +21,13 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
+    # - name: Cleanup Disk
+    #   run: |
+    #     sudo rm -rfv /usr/local/lib/android || true
+    #     sudo rm -rfv /opt/ghc || true
+    #     sudo rm -rfv /usr/local/.ghcup || true
     - name: Cleanup Disk
-      run: |
-        sudo rm -rfv /usr/local/lib/android || true
-        sudo rm -rfv /opt/ghc || true
-        sudo rm -rfv /usr/local/.ghcup || true
+      uses: wimpysworld/nothing-but-nix@main
 
     - name: Install Doppler CLI
       uses: dopplerhq/cli-action@v3
@@ -72,11 +74,13 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
+    # - name: Cleanup Disk
+    #   run: |
+    #     sudo rm -rfv /usr/local/lib/android || true
+    #     sudo rm -rfv /opt/ghc || true
+    #     sudo rm -rfv /usr/local/.ghcup || true
     - name: Cleanup Disk
-      run: |
-        sudo rm -rfv /usr/local/lib/android || true
-        sudo rm -rfv /opt/ghc || true
-        sudo rm -rfv /usr/local/.ghcup || true
+      uses: wimpysworld/nothing-but-nix@main
 
     - name: Install Doppler CLI
       uses: dopplerhq/cli-action@v3
